name: Daily Solar Report

on:
  schedule:
    - cron: '00 13 * * *'  # 10h heure de Tunis (UTC+2)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run report
      run: python solar_report.py
      env:
        EMAIL: ${{ secrets.EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        DEST: ${{ secrets.DEST }}
